#!/bin/sh

#This script submits workerscript (an FSL-jobscript for ABEL) to the cluster. 
#Remember:
#	to set the arraryrun numbers to the participants of the study. 
#	to run the script from where you would like the feat output directory to be. 

#SBATCH --account=uio
#
#SBATCH --time=50:0:0
#
#SBATCH --mem-per-cpu=200M

source /cluster/bin/jobsetup

module purge   # clear any inherited modules
set -o errexit # exit on errors

arrayrun 515,632 workerscript
