#!/bin/bash

##Notes
#	Remember to implement the lowpri queue in this script.

#SBATCH --account=uio
#SBATCH --time=2:0:0
#SBATCH --mem-per-cpu=2G

source /cluster/bin/jobsetup

module purge	# clear any inherited modules
set -o errexit	# exit on errors

module load fsl/5.0.9	# Will load FSL in ABEL (check using module avail).

source $FSLDIR/etc/fslconf/fsl.sh

DATASET="/usit/abel/u1/pedermi/Opioidfmri/standard_space/MNI152_T1_2mm_brain.nii.gz /usit/abel/u1/pedermi/Opioidfmri/checker/fMRI_raw/Session1/$TASK_ID/fmri.nii.gz /usit/abel/u1/pedermi/Opioidfmri/BET/$TASK_ID/3DRR_brain.nii.gz /usit/abel/u1/pedermi/Opioidfmri/checker/EVs/$TASK_ID/Session1/checker.txt /usit/abel/u1/pedermi/Opioidfmri/checker/scripts/firstFEAT.fsf"
OUTFILE=$SCRATCH/$TASK_ID.feat

cp $DATASET $SCRATCH
cd $SCRATCH
chkfile $OUTFILE

#mkdir $OUTFILE
#ls > $OUTFILE/data.txt
#echo "SCRATCH=$SCRATCH OUTFILE=$OUTFILE TASK_ID=$TASK_ID" > $OUTFILE/variables.txt

sed -ie "s|OUTFILE|${OUTFILE}|g" firstFEAT.fsf #Replace "OUTFILE" with the path of the actual OUTFILE directory. 
sed -ie "s|SCRATCH|${SCRATCH}|g" firstFEAT.fsf #Replace "SCRATCH" with the path of the actual SCRATCH directory. 
#sed -ie "s|featwatcher_yn) 1|featwatcher_yn 0|g" firstFEAT.fsf #test if opening html is crashing script" 

#cp firstFEAT.fsf $OUTFILE

feat firstFEAT.fsf
