#!/bin/bash

##Notes
#	

#SBATCH --job-name=secondfeat
#SBATCH --account=uio
#SBATCH --time=60:0:0
#SBATCH --mem-per-cpu=4G

source /cluster/bin/jobsetup

#SBATCH --output=secondfeat
#SBATCH --error=secondfeat_error

module purge	# clear any inherited modules
set -o errexit	# exit on errors

module load fsl/5.0.9	# Will load FSL in ABEL (check using module avail).

source $FSLDIR/etc/fslconf/fsl.sh

DATASET="/usit/abel/u1/pedermi/Opioid_Reward_fMRI/checkerboard/FEAT/firstlevel/Session*/501.feat /usit/abel/u1/pedermi/Opioid_Reward_fRMI/checkerboard/FEAT/firstlevel/Session*/502.feat /usit/abel/u1/pedermi/Opioid_Reward_fMRI/checkerboard/scripts/FEAT_second/temp/FEAT_temp.fsf"
OUTFILE=$SCRATCH/secondfeat.feat

cp -r $DATASET $SCRATCH
cd $SCRATCH
chkfile $OUTFILE

mkdir $OUTFILE
ls > $OUTFILE/data.txt
echo "SCRATCH=$SCRATCH OUTFILE=$OUTFILE TASK_ID=$TASK_ID" > $OUTFILE/variables.txt

sed -ie "s|OUTFILE|${OUTFILE}|g" firstFEAT.fsf #Replace "OUTFILE" with the path of the actual OUTFILE directory. 
sed -ie "s|SCRATCH|${SCRATCH}|g" firstFEAT.fsf #Replace "SCRATCH" with the path of the actual SCRATCH directory. 

feat FEAT_temp.fsf
