#!/bin/bash

##Notes
#	

#SBATCH --job-name=secondfeat
#SBATCH --account=uio
#SBATCH --time=2:0:0
#SBATCH --mem-per-cpu=1G
#SBATCH --qos=lowpri

source /cluster/bin/jobsetup

module purge	# clear any inherited modules
set -o errexit	# exit on errors

module load fsl/5.0.9	# Will load FSL in ABEL (check using module avail).

source $FSLDIR/etc/fslconf/fsl.sh


DATASET_S1="/usit/abel/u1/pedermi/Opioid_Reward_fMRI/checkerboard/FEAT/firstlevel/Session1/501.feat /usit/abel/u1/pedermi/Opioid_Reward_fMRI/checkerboard/FEAT/firstlevel/Session1/502.feat"
DATASET_S2="/usit/abel/u1/pedermi/Opioid_Reward_fMRI/checkerboard/FEAT/firstlevel/Session2/501.feat /usit/abel/u1/pedermi/Opioid_Reward_fMRI/checkerboard/FEAT/firstlevel/Session2/502.feat"
FEAT_FILE="/usit/abel/u1/pedermi/Opioid_Reward_fMRI/checkerboard/scripts/FEAT_second/temp/FEAT_temp.fsf"
OUTFILE=$SCRATCH/secondfeat.gfeat


mkdir $SCRATCH/Session1 $SCRATCH/Session2
cp -r $DATASET_S1 $SCRATCH/Session1
cp -r $DATASET_S2 $SCRATCH/Session2
cp -r $FEAT_FILE $SCRATCH

cd $SCRATCH
chkfile $OUTFILE

mkdir $OUTFILE
ls > $OUTFILE/data.txt
ls Session1/501.feat >> $OUTFILE/data.txt


sed -ie "s|OUTFILE|${OUTFILE}|g" FEAT_temp.fsf #Replace "OUTFILE" with the path of the actual OUTFILE directory. 
sed -ie "s|SCRATCH|${SCRATCH}|g" FEAT_temp.fsf #Replace "SCRATCH" with the path of the actual SCRATCH directory. 


feat FEAT_temp.fsf
