#!/bin/bash

##Notes:
#
# This is a job script for Abel. Lines starting with #SBATCH are not commented out - they are read
# specifically by the computer cluster. 


#SBATCH --job-name=MORvsPLA_simple
#SBATCH --account=uio
#SBATCH --time=24:0:0
#SBATCH --mem-per-cpu=4G

source /cluster/bin/jobsetup

#SBATCH --output=MORvsPLA_simple
#SBATCH --error=MORvsPLA_simple_error

module purge	# clear any inherited modules
set -o errexit	# exit on errors

module load fsl/5.0.9	# Will load FSL in ABEL (check using module avail).

source $FSLDIR/etc/fslconf/fsl.sh

DATASET="/usit/abel/u1/pedermi/Opioid_Reward_fMRI/checkerboard/FEAT/firstlevel/Session* /usit/abel/u1/pedermi/Opioid_Reward_fMRI/checkerboard/scripts/FEAT_second/MORvsPLA_simple.fsf"
OUTFILE=$SCRATCH/MORvsPLA_simple.gfeat

cp -r $DATASET $SCRATCH
cd $SCRATCH
chkfile $OUTFILE


sed -ie "s|OUTFILE|${OUTFILE}|g" MORvsPLA_simple.fsf #Replace "OUTFILE" with the path of the actual OUTFILE directory. 
sed -ie "s|SCRATCH|${SCRATCH}|g" MORvsPLA_simple.fsf #Replace "SCRATCH" with the path of the actual SCRATCH directory. 

feat MORvsPLA_simple.fsf
