#!/bin/bash

##Notes:
#
# This is a job script for Abel. Lines starting with #SBATCH are not commented out - they are read
# specifically by the computer cluster. 


#SBATCH --job-name=MORvsPLA_autodw_minus532
#SBATCH --account=uio
#SBATCH --time=48:0:0
#SBATCH --mem-per-cpu=4G
#SBATCH --output=MORvsPLA_autodw_minus532_%j.slurm
#SBATCH --error=MORvsPLA_autodw_minus532_error_%j.slurm

source /cluster/bin/jobsetup

module purge	# clear any inherited modules
set -o errexit	# exit on errors

module load fsl/5.0.9	# Will load FSL in ABEL (check using module avail).

source $FSLDIR/etc/fslconf/fsl.sh

DATASET="/usit/abel/u1/pedermi/Opioid_Reward_fMRI/checkerboard/FEAT/firstlevel/Session* /usit/abel/u1/pedermi/Opioid_Reward_fMRI/checkerboard/scripts/FEAT_secondlvl/MORvsPLA_autodw_minus532.fsf"
OUTFILE=$SCRATCH/MORvsPLA_autodw_minus532.gfeat

cp -r $DATASET $SCRATCH
cd $SCRATCH
chkfile $OUTFILE

sed -ie "s|OUTFILE|${OUTFILE}|g" MORvsPLA_autodw_minus532.fsf #Replace "OUTFILE" with the path of the actual OUTFILE directory. 
sed -ie "s|SCRATCH|${SCRATCH}|g" MORvsPLA_autodw_minus532.fsf #Replace "SCRATCH" with the path of the actual SCRATCH directory. 

feat MORvsPLA_autodw_minus532.fsf
